# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/Thesis.ipynb.

# %% auto 0
__all__ = ['strategy_invest']

# %% ../nbs/Thesis.ipynb 3
from .arima_stats import create_auto_arima_prediction_future_2
from .arima_stats import create_dataframe_with_series
from .arima_stats import top_score
from .arima_stats import get_top_players
from .arima_stats import create_dataframe
import buy_and_hold_vs_arima
import yfinance as yf
import pandas as pd 
import numpy as np 

# %% ../nbs/Thesis.ipynb 17
def strategy_invest(func, series_data , future = 30):
    change_invest_arr = pd.date_range('2017-12-31', freq="M", periods=5*12 -1) # 5 years in months
    capital = 100
    for current_date,next_date in zip(change_invest_arr,change_invest_arr[1:]):
        df , relative_diff = get_revenue_arima(create_auto_arima_prediction_future_2 , series_data.loc[:current_date],future=30)
        real_relative_diff = show_all_difference(series_data.loc[current_date:].iloc[0],series_data.loc[next_date:].iloc[0])
        if relative_diff > 0:
            capital *= (1+real_relative_diff)
        print("----------------------------------------------------------")
        print("expected relative diff : ", relative_diff)
        print("Da facto Revenue/loss " , )
        print("current date : " , current_date)
        print("current capital: " , capital)
    
